auth_enabled: false
server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /var/loki/wal    # ✅ เปลี่ยนจาก /wal

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v12
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/boltdb-cache
  filesystem:
    directory: /var/loki/chunks

compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem
  compactor_ring:
    kvstore:
      store: inmemory

limits_config:
  ingestion_rate_strategy: local
  ingestion_burst_size_mb: 16

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
