{
 "title": "Express API Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS by Route",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * sum(rate(http_request_duration_seconds_count{code=~\"(4..|5..)\"}[5m]))\n/ sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le, route) (rate(http_request_duration_seconds_bucket[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by (le) (rate(http_request_duration_seconds_bucket[5m]))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs & Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"app_logs\"} | json | path!=\"/metrics\""
    }
   ]
  },
  {
   "title": "Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "filters": [
      { "id": "ee88f167", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "express-api" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "query": "{resource.service.name=\"express-api\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}